name: text_extension
description: An extension to the Text widget that helps to reduce the boilerplate and adds some helpful methods.
version: 0.0.1
author: Thalles Santos <thalles.rss@gmail.com>
homepage: https://github.com/thallessantos/text_extension

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
